######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 6 13:15:56 2016
######################################################################

QT += widgets

CONFIG += c++11
INCLUDEPATH += ../engine
LIBS += -L../engine -lengine

HEADERS       = window.h
SOURCES       = main.cpp \
                window.cpp
