######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 4 18:29:09 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
